INSERT INTO mouse (id, brand, model)
VALUES (gen_random_uuid(), 'Logitech', 'G PRO X Superlight'),
       (gen_random_uuid(), 'Logitech', 'G PRO X Superlight 2'),
       (gen_random_uuid(), 'Logitech', 'PRO X2 Superstrike'),
       (gen_random_uuid(), 'Logitech', 'G502 Lightspeed'),
       (gen_random_uuid(), 'Logitech', 'G502 HERO'),
       (gen_random_uuid(), 'Logitech', 'G305 Lightspeed'),
       (gen_random_uuid(), 'Razer', 'Viper V2 Pro'),
       (gen_random_uuid(), 'Razer', 'Viper V3 Pro'),
       (gen_random_uuid(), 'Razer', 'Viper V4 Pro'),
       (gen_random_uuid(), 'Endgame Gear', 'OP1 8k v2'),
       (gen_random_uuid(), 'Endgame Gear', 'OP1w 4k v2'),
       (gen_random_uuid(), 'LAMZU', 'MAYA'),
       (gen_random_uuid(), 'LAMZU', 'MAYA X'),
       (gen_random_uuid(), 'LAMZU', 'ATLANTIS Mini'),
       (gen_random_uuid(), 'Pulsar', 'X2 CrazyLight Mini'),
       (gen_random_uuid(), 'Pulsar', 'X2 CrazyLight Medium'),
       (gen_random_uuid(), 'Pulsar', 'X2N CrazyLight Mini'),
       (gen_random_uuid(), 'Pulsar', 'X2N CrazyLight Medium'),
       (gen_random_uuid(), 'Pulsar', 'X2H CrazyLight Mini'),
       (gen_random_uuid(), 'Pulsar', 'X2H CrazyLight Medium'),
       (gen_random_uuid(), 'WLMOUSE', 'Beast X'),
       (gen_random_uuid(), 'WLMOUSE', 'Beast X Mini'),
       (gen_random_uuid(), 'WLMOUSE', 'Beast X Max'),
       (gen_random_uuid(), 'WLMOUSE', 'Beast X Pro'),
       (gen_random_uuid(), 'ATK', 'A9'),
       (gen_random_uuid(), 'ATK', 'A9 Ultimate'),
       (gen_random_uuid(), 'ATK', 'A9 Air'),
       (gen_random_uuid(), 'ATK', 'Blazing Sky F1 V2'),
       (gen_random_uuid(), 'ATK', 'Blazing Sky X1 V2'),
       (gen_random_uuid(), 'VXE', 'Dragonfly R1'),
       (gen_random_uuid(), 'VXE', 'MAD R'),
       (gen_random_uuid(), 'Ninjutso', 'Sora V2'),
       (gen_random_uuid(), 'Ninjutso', 'Sora V3'),
       (gen_random_uuid(), 'VAXEE', 'NP-01S V3'),
       (gen_random_uuid(), 'VAXEE', 'NP-01S V2'),
       (gen_random_uuid(), 'VAXEE', 'NP-01'),
       (gen_random_uuid(), 'VAXEE', 'XE-S'),
       (gen_random_uuid(), 'MCHOSE', 'L7'),
       (gen_random_uuid(), 'MCHOSE', 'L7 Pro'),
       (gen_random_uuid(), 'MCHOSE', 'L7 Pro+'),
       (gen_random_uuid(), 'MCHOSE', 'L7 Ultra'),
       (gen_random_uuid(), 'MCHOSE', 'L7 Ultra+'),
       (gen_random_uuid(), 'MCHOSE', 'A7'),
       (gen_random_uuid(), 'MCHOSE', 'A7 Pro'),
       (gen_random_uuid(), 'MCHOSE', 'A7 Ultra'),
       (gen_random_uuid(), 'Hitscan', 'Hyperlight');

INSERT INTO mousepad(id, brand, model)
VALUES (gen_random_uuid(), 'Artisan', 'Ninja FX Zero XSOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Zero SOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Zero MID'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Hien XSOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Hien SOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Hien MID'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Raiden XSOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Raiden SOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Raiden MID'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Type-99 XSOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Type-99 SOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Type-99 MID'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Key-83 XSOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Key-83 SOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Key-83 MID'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Hayate Otsu XSOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Hayate Otsu SOFT'),
       (gen_random_uuid(), 'Artisan', 'Ninja FX Hayate Otsu MID'),
       (gen_random_uuid(), 'Logitech', 'G640'),
       (gen_random_uuid(), 'Logitech', 'G440'),
       (gen_random_uuid(), 'Logitech', 'G740'),
       (gen_random_uuid(), 'Logitech', 'G240'),
       (gen_random_uuid(), 'Logitech', 'G840'),
       (gen_random_uuid(), 'Razer', 'Strider'),
       (gen_random_uuid(), 'Razer', 'Atlas'),
       (gen_random_uuid(), 'Razer', 'Gigantus V2 Pro Max Control'),
       (gen_random_uuid(), 'Razer', 'Gigantus V2 Pro Control'),
       (gen_random_uuid(), 'Razer', 'Gigantus V2 Pro Balance'),
       (gen_random_uuid(), 'Razer', 'Gigantus V2 Pro Speed'),
       (gen_random_uuid(), 'Razer', 'Gigantus V2 Pro Max Speed'),
       (gen_random_uuid(), 'SteelSeries', 'QcK'),
       (gen_random_uuid(), 'SteelSeries', 'QcK Heavy'),
       (gen_random_uuid(), 'SteelSeries', 'QcK Performance Balance'),
       (gen_random_uuid(), 'SteelSeries', 'QcK Performance Control'),
       (gen_random_uuid(), 'SteelSeries', 'QcK Performance Speed'),
       (gen_random_uuid(), 'Wallhack', 'SP-005'),
       (gen_random_uuid(), 'Wallhack', 'CR-005'),
       (gen_random_uuid(), 'Wallhack', 'VA-005');

INSERT INTO skates(id, brand, model)
VALUES (gen_random_uuid(), 'X-Raypad', 'Jade'),
       (gen_random_uuid(), 'X-Raypad', 'Jade Air'),
       (gen_random_uuid(), 'X-Raypad', 'Jade Ultra'),
       (gen_random_uuid(), 'X-Raypad', 'Obsidian'),
       (gen_random_uuid(), 'X-Raypad', 'Obsidian PRO Air'),
       (gen_random_uuid(), 'X-Raypad', 'Obsidian Air'),
       (gen_random_uuid(), 'ESPTiger', 'Ice V2'),
       (gen_random_uuid(), 'MGG', 'Ultraglide Ice'),
       (gen_random_uuid(), 'MGG', 'Ultraglide RS'),
       (gen_random_uuid(), 'MGG', 'Ultraglide Speed'),
       (gen_random_uuid(), 'MGG', 'Ultraglide Control'),
       (gen_random_uuid(), 'Westlab', 'Black'),
       (gen_random_uuid(), 'Westlab', 'Orange'),
       (gen_random_uuid(), 'Westlab', 'Cream'),
       (gen_random_uuid(), 'Westlab', 'Blue'),
       (gen_random_uuid(), 'Westlab', 'White'),
       (gen_random_uuid(), 'Westlab', 'Yellow'),
       (gen_random_uuid(), 'Westlab', 'Grey'),
       (gen_random_uuid(), 'PMM', 'Smoothies'),
       (gen_random_uuid(), 'Artisan', 'Mizugumo Futae P6'),
       (gen_random_uuid(), 'Artisan', 'Mizugumo Futae P8');




